version: "3.8"

services:
  flight_mysql:
    image: mysql:latest
    container_name: flight_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: New123
      MYSQL_DATABASE: flight_reservation
    ports:
      - "3300:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flight_redis:
    image: redis:latest
    container_name: flight_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
